export const UI_PLANET_EMPTY = "UI_PLANET_EMPTY";
export const UI_PLANET_FAILED = "UI_PLANET_FAILED";
export const UI_PLANET_SAVE = "UI_PLANET_SAVE";
export const UI_PLANET_START = "UI_PLANET_START";
export const UI_PLANET_SUCCESS = "UI_PLANET_SUCCESS";

export const UI_VEHICLE_EMPTY = "UI_VEHICLE_EMPTY";
export const UI_VEHICLE_FAILED = "UI_VEHICLE_FAILED";
export const UI_VEHICLE_SAVE = "UI_VEHICLE_SAVE";
export const UI_VEHICLE_START = "UI_VEHICLE_START";
export const UI_VEHICLE_SUCCESS = "UI_VEHICLE_SUCCESS";



